name: Lint and Style Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Set up project
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Run pylint
        run: |
          source .venv/bin/activate
          pylint app

